version: '2'

services:
  nginx:
    image: nginx:1.11
    ports:
      - "8080:80"
    environment:
     - NGINX_PORT=80
    volumes:
      - /DATA/nginx/brigde:/brigde
    command: /bin/bash -c "echo $PATH"
    links:
      - redis
      - tomcat
      - mysql
  tomcat:
    image: tomcat:jre8
    ports:
      - "8180:8080"
    volumes:
      - /DATA/tomcat/brigde:/brigde
  redis:
    image: redis:3
    ports:
      - "6400:6379"
    volumes:
      - /DATA/redis/brigde:/brigde
  mysql:
    image: mysql:8
    volumes:
       - /DATA/mysql/db_data:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
  wordpress:
     depends_on:
       - mysql
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_PASSWORD: wordpress