version: '2'

services:
  tomcat:
    image: tomcat:jre8
    restart: always
    ports:
      - "8280:8080"
    volumes:
      - /DATA/playSpring/tomcat/bridge:/bridge
    depends_on:
       - mysql
  mysql:
    image: mysql:8
    restart: always
    volumes:
       - /DATA/playSpring/mysql/db_data:/var/lib/mysql
    restart: always
    ports:
      - "3400:3306"
    environment:
       MYSQL_ROOT_PASSWORD: playSpring
       MYSQL_DATABASE: playSpring
       MYSQL_USER: playSpring
       MYSQL_PASSWORD: playSpring