version: '2'

services:
  example:
    image: nginx:1.11
    ports:
      - "8180:8080"
    volumes:
      - /DATA/nginx/brigde:/brigde
    links:
      - redis
      - tomcat
  tomcat:
    image: tomcat:jre8
    ports:
      - "8180:8080"
      - /DATA/tomcat/brigde:/brigde
  redis:
    image: redis:3
    ports:
      - "6400:6379"
    volumes:
      - /DATA/redis/brigde:/brigde