version: '2'

services:
  nginx:
    image: nginx:1.11
    restart: always
    ports:
      - "80:80"
    environment:
     - NGINX_PORT=80
    volumes:
      - /DATA/nginx/brigde:/brigde
    command: /bin/bash -c "echo $PATH"
    links:
      - redis
      - tomcat
  tomcat:
    image: tomcat:jre8
    restart: always
    ports:
      - "8280:8080"
    volumes:
      - /DATA/tomcat/bridge:/bridge
  redis:
    image: redis:3
    restart: always
    ports:
      - "6400:6379"
    volumes:
      - /DATA/redis/brigde:/brigde
  