version: '2'

services:
  tomcat:
    image: tomcat:jre8
    restart: on-failure:5
    ports:
      - "8280:8080"
    volumes:
      - /DATA/playSpring/tomcat/bridge:/bridge
    depends_on:
       - mysql
  mysql:
    image: mysql:8
    restart: on-failure:5
    volumes:
       - /DATA/playSpring/mysql/db_data:/var/lib/mysql
    ports:
      - "3400:3306"
    environment:
       MYSQL_ROOT_PASSWORD: playSpring
       MYSQL_DATABASE: playSpring
       MYSQL_USER: playSpring
       MYSQL_PASSWORD: playSpring
  mongodb:
    image: mongo:3.2
    restart: on on-failure:5
    volumes: 
      - /DATA/playSpring/mongodb/db:/data/db
    ports:
      - "3500:27017"
    command: --auth
    environment:
      MONGODB_USER: playSpring
      MONGODB_DATABASE: playSpring
      MONGODB_PASS: playSpring
  redis:
    image: redis:3
    restart: on-failure:5
    ports:
      - "6400:6379"
    volumes:
      - /DATA/playSpring/redis/brigde:/brigde

