version: '2'

services:
  example:
    image: ngix:1.11
    ports:
      - "8180:8080"
    volumes:
      - /DATA/tomcat/brigde:/brigde
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6400:6379"