version: '2'

services:
  nginx:
    image: nginx:1.11
    ports:
      - "80:80"
    environment:
     - NGINX_PORT=80
    volumes:
      - /DATA/blacktea/nginx/brigde:/brigde
    command: /bin/bash -c "echo $PATH"
    links:
      - tomcat
      - mysql
      - redis
  tomcat:
    image: tomcat:jre8
    restart: always
    ports:
      - "8280:8080"
    volumes:
      - /DATA/blacktea/tomcat/bridge:/bridge
  mysql:
    image: mysql:8
    restart: always
    volumes:
       - /DATA/blacktea/mysql/db_data:/var/lib/mysql
    restart: always
    ports:
      - "3400:3306"
    environment:
       MYSQL_ROOT_PASSWORD: blacktea
       MYSQL_DATABASE: blacktea
       MYSQL_USER: blacktea
       MYSQL_PASSWORD: blacktea
  redis:
    image: redis:3
    restart: always
    ports:
      - "6400:6379"
    volumes:
      - /DATA/blacktea/redis/brigde:/brigde
  