version: '2'

services:
  tomcat:
    image: tomcat:jre8
    ports:
      - "8180:8080"
    volumes:
      - /DATA/tomcat/brigde:/brigde
  # nginx:
  #   image: nginx:1.11
  #   ports:
  #     - "8080:80"
  #   environment:
  #    - NGINX_PORT=80
  #   volumes:
  #     - /DATA/nginx/brigde:/brigde
  #   command: /bin/bash -c "echo $PATH"
  #   links:
  #     - redis
  #     - tomcat
  #     - mysql
  #     - wordpress
  # tomcat:
  #   image: tomcat:jre8
  #   ports:
  #     - "8180:8080"
  #   volumes:
  #     - /DATA/tomcat/brigde:/brigde
  # redis:
  #   image: redis:3
  #   ports:
  #     - "6400:6379"
  #   volumes:
  #     - /DATA/redis/brigde:/brigde
  