version: '2'

services:
  ss-demo:
    image: registry.cn-hangzhou.aliyuncs.com/mrjin/shadowsocks
    ports:
      - "8888:8888"
    restart: always
    environment:
     - PASSWORD=jin123
     - SERVER_PORT=8888
     - METHOD=aes-256-cfb
  ss-demo:
    image: registry.cn-hangzhou.aliyuncs.com/mrjin/shadowsocks
    ports:
      - "8999:8888"
    restart: always
    environment:
     - PASSWORD=jin123
     - SERVER_PORT=8888
     - METHOD=aes-256-cfb